a = input('Digite: ')
print(f'O tipo primitivo é: {type(a)}')
print(f'Is space? {a.isspace()}')
print(f'Is numeric? {a.isnumeric()}')
print(f'Is alpha? {a.isalpha()}')
print(f'Is alphanum? {a.isalnum()}')
print(f'Is upper? {a.isupper()}') 
print(f'Is lower? {a.islower()}') 
print(f'Is title? {a.istitle()}') 